spring:
  application:
    name: ticket
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket
    username: postgres
    password: gernika54
server:
  port: 8005
  servlet:
    context-path: /ticket/api/
