spring:
  application:
    name: store
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: gernika54
server:
  port: 8001
  servlet:
    context-path: /store/api/
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: api-docs
