openapi: 3.0.1
info:
  title: MNS
  description: 'MNS subscription'
  version: 1.0.0
servers:
  - url: http://localhost:8004/com/diy/subscription/v1
tags:
  - name: subscription
    description: Everything about subscriptions
paths:
  /path:

components:
  schemas:
