server:
  port: 8761
  ssl:
    enabled: false

spring:
  application:
    name: ${SERVICE_NAME:eureka-server}

eureka:
  instance:
    hostname: ${SERVICE_NAME:localhost}
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/