spring:
  application:
    name: subscription
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription
    username: postgres
    password: gernika54
server:
  port: 8004
  servlet:
    context-path: /subscription/api/
