spring:
  application:
    name: customer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: gernika54
server:
  port: 8006
  servlet:
    context-path: /customer/api/
