#!/usr/bin/env python3
import sys
import os


def main():
    GROUP_ID = os.getenv("GROUP_ID")
    if not GROUP_ID:
        return 1
    SRV = os.getenv("SRV")
    if not SRV:
        return 1
    sys.stdout.write(", ".join([f"{GROUP_ID}:{i}" for i in SRV.split(" ") if i]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
